### ISSUE TITLE
midterm-if.py is ready

### ISSUE THREAD

**Issue by jttreichel** [madisoncollege-it-programs/python-scripting-jttreichel#10]

**Comment by cethenmc** [comment]
All concepts you used were concepts learned in class, which was nice to see.  I like that you analyzed your data carefully to identify the column structure in the flat file.  Perhaps you had to analyze too much to creatively come up with the correct line numbers.  What would you have done if the file ID's went up to the ten-thousands, or Kayley's record started with an ID of 1?  Any coding to finite field lengths can be faulty, so be careful.  Still, you extracted line numbers and converted them to int, as requested.  Therefore, I can't take away points based on the language in the assignment, but I encourage you to figure out a single way to accomplish the same given the question I listed earlier.    There is a lot of unnecessary noise in your script, and you should clean your script before submitting.  I am unsure why variables were reset for every iteration in your for loop, why you kept adding 0 to your total for every iteration in your for loop, and especially why you kept setting "line = h.readlines()" within each iteration (readlines() was already read, so if you read anymore it is empty)?  If you comment out all of those eight lines, your script would run the same (3 pts).  Your output did not include your name (1 pt).  Your score is 29 of 33.
