### ISSUE TITLE
midterm-slicing.py is ready

### ISSUE THREAD

**Issue by jttreichel** [madisoncollege-it-programs/python-scripting-jttreichel#12]

**Comment by cethenmc** [comment]
Wow!  So very close to bringing it home.  You made this more complicated than it had to be with your tuples, but you still almost made it work your way.  If you had just added .replace("\\n","") to the o in your print line, you would have had it (1 pt).  However, I still am taking off a point for the lack of well labeled variables (1 pt).  Make your variable names descriptive enough so I know you obviously know what things are.  32/34.
