### ISSUE TITLE
week 10 assignment ready for grading

### ISSUE THREAD

**Issue by jttreichel** [madisoncollege-it-programs/python-scripting-jttreichel#14]

**Comment by cethenmc** [comment]
I will not dock for this on the lab, but on the Final it would ding you slightly.  Instead of this...

myProcSlice = myProcList[1:**500**:1]

...it should be this...

myProcSlice = myProcList[1::1]

Not putting in a number for the stop will take it to the end of the file. 

8 of 8 recorded.
