### ISSUE TITLE
Final Exam complete

### ISSUE THREAD

**Issue by jttreichel** [madisoncollege-it-programs/python-scripting-jttreichel#19]

**Comment by cethenmc** [comment]
Nice final.  In the first bullet for Function 4, you somewhat missed two points.  However, I looked at your grade and noticed you selected not to correct your Argparse Lab in Week 11.  By my taking off only 1 point for that bullet on Function 4, if you want, you could move your AB to an A (after rounding) by completing that lab perfectly.  You can reopen that GitHub Issue Ticket for week 11.  Please email me if you plan to complete that before tomorrow night at midnight.  It has been fantastic having you in class!

![image](https://user-images.githubusercontent.com/112707666/207651088-1c2d8f1d-c60e-4296-a3d5-0222fa7b76e7.png)

**Comment by jttreichel** [comment]
I have made changes to week 11 lab according to the assignment and submitted a new issue in GitHub.
Thanks for a great class this semester. I learned a lot!
________________________________
