### ISSUE TITLE
week2 first script assignment ready for grading

### ISSUE THREAD

**Issue by jttreichel** [madisoncollege-it-programs/python-scripting-jttreichel#2]

**Comment by cethenmc** [comment]
Hi, Jacob. For Week 2, Assignment https://github.com/madisoncollege-it-programs/python-scripting-cpsaffold/issues/2 (first-script.py)...

I would like you to update your script so you can run it from the command line.

Your first line should always be the following for your scripts. In this way, if you are running from the command line it will know what interpreter to use. Will you please add this line to the top of your first-script.py code?

#!/usr/bin/env python3

Recall from the videos, you may also need to issue a chmod command to modify the rights to make it executable.

chmod u+x first-script.py

After this, you can execute from the command line.

./first-script.py

Please be so kind as to resubmit it, so...
1. modify the file in NetLab with the added line at the top.
2. update the file to be executable.
3. add the file to staging (git add .)
4. commit the file to your local repo. (git commit -m "changes requested to run from command line")
5. push to the git hub repository (git push)
6. reply to this same issue, saying you have completed these steps

Thanks.

~Chris

**Comment by jttreichel** [comment]
I made the changes and pushed it to GitHub. Thank you for the feedback. sorry for the late response.

**Comment by cethenmc** [comment]
Thanks for correcting it.  It looks fine now!
