### ISSUE TITLE
week5 ready for grading

### ISSUE THREAD

**Issue by jttreichel** [madisoncollege-it-programs/python-scripting-jttreichel#6]

**Comment by cethenmc** [comment]
Jacob - Nice effort, but way too much noise in the output for this.  You printed out much more than asked for, so it makes it difficult to grade.  
Unless you do multiline prints for your reasons, the output from this script should be just 8 lines long.

You are not required to loop for the first two at all, and it looks like you could definitely use a hand on the third.  Please also place the author (your name), and a short description right after the interpreter line at the top of the file.

Please book me through Blackboard under Instructor Contact.  However, if none of these times work, email me with several times you can make work, and we will try to find a mutual time.  Thanks. ~Chris

**Comment by jttreichel** [comment]
I booked for 1:15 on monday.

Thanks!

Jacob
________________________________

**Comment by cethenmc** [comment]
Excellent.  Hopefully, you can continue to work on the midterm parts that you are solid on since they are all due Thursday.  The concept we will cover in our Monday meeting should not take us long.

Please let me also know if your booking created an appointment on your calendar.  If it didn't, I would forward the one I received.

Thanks.

Chris

[signature_146958654]
Chris Ethen| Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>

**Comment by jttreichel** [comment]
I don't see the booking appointment on my calander.
________________________________

**Comment by cethenmc** [comment]
Thank you, Jacob.  I just forwarded the one I got, so hopefully, you see that one, too.

Chris

[signature_146958654]
Chris Ethen| Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>

**Comment by cethenmc** [comment]
Hi, Jacob.  I will give full credit, but I think you could have elaborated on this answer better for readlines():  "This could be used for reading files that are too large to use the read function."  This is not true.  Did you look at the slide (Slide #15) like I asked?  If not, please review it.  I will lift the score to 7 for 8 for now, but please feel free to rewrite that explanation, re-push to GitHub, and reply to this Issue when it is ready for me to recheck.  Thanks.  ~Chris

**Comment by jttreichel** [comment]
Hi, 
Thanks for the feedback. I did review slide #15. I mistakenly read the descriptions out of order and gave an inaccurate description for step 2. I made a correction and resubmitted to github. thanks for all the help.
