### ISSUE TITLE
Dictionaries lab ready for grading.

### ISSUE THREAD

**Issue by jttreichel** [madisoncollege-it-programs/python-scripting-jttreichel#9]

**Comment by cethenmc** [comment]
As we discussed over the phone, I have marked this as a 7 of 8 in the gradebook for now.  You plan to rework the assignment creating a simpler dictionary of addresses = {"server1.testlab.com" : "192.168.1.10", "server2.testlab.com" : "192.168.1.11", etc...}.  Please reply to this Issue Ticket when you have pushed your changes to GitHub for grading.  Thanks. ~Chris

**Comment by jttreichel** [comment]
I made a simpler dictionary and made the changes to week7 lab script.

**Comment by cethenmc** [comment]
Yay!  I like this one so much better!  Full credit.  nice work.
